LogIn: Login
LogOut: Logout
Register: Register
Notifications: Notifications
ActiveCompetitions: Active competitions
OpenSignUps: Open sign-ups
PastCompetitions: Past competitions
FutureCompetitions: Future competitions
Results: Results
Back: Back
Hole: Hole
Round: Round
Total: Total
MPO: Open
FPO: Women
MPM: Master
MJ1: Junior-18
MJ2: Junior-15
MA2: Amateur Intermediate
MA3: Amateur Recreational
Password: Password
Courses: Courses
Series: Series
Users: Users
Homepage: Homepage
NewCompetition: New competition
NewCourse: New course
Layouts: Layouts
Pars: Pars
HeadAdmins: Head Admins
Admins: Admins
AddCourse: Add course
CourseName: Course name
AddSerie: Add serie
SerieName: Serie name
AddCompetition: Add competition
Layout: Layout
Date: Date
CompetitionName: Competition name
PlayerLimit: Player limit
Notification: Notification
AddNotification: Add notification
Admin: Admin
Update: Update
Name: Name
Email: Email
Division: Division
Divisions: Divisions
SignUp: Sign up
FinishCompetition: Finish competition
NextRound: Next round
StartCompetition: Start competition
UpdateLayout: Update layout
AddLayout: Add layout
LayoutName: Layout name
LayoutDesc: Layout description
NumberOfHoles: Number of holes
NotAdmin: You must be an admin
NotSuperAdmin: You must be a super admin
SignUpSuccess: Signed up succesfully
SignUpFail: Sign up failed
SignUpWrongPassword: Incorrect competition password
UserUpdatedSuccess: User updated
FormMissing: Error: Form missing
FormFailure err@Text: Error: #{err}
NotPresent: Not present
Present: Present
Information: Information
AdminPanel: Admin panel
WrongAnswer: Wrong answer
ReloadPage: Reload the page automatically
DNF: DNF
CompetitionAdded: Competition added
CompetitionStarted: Competition started
CompetitionFinished: Competition finished
NextRoundChanged: Next round changed
NextRoundScoresMissing: Next round could not be changed because not all scores have been inserted
FinishCompetitionScoresMissing: Competition could not be finished because not all scores have been inserted
ProfileUpdated: Profile updated
ProfileUpdateFailure: Profile update failed
Profile: Profile
NotificationAdded: Notification added
SerieAdded: Serie added
CourseAdded: Course added
LayoutAdded: Layout added
LayoutUpdated: Layout updated
Group: Group
Send: Send
CurrentPassword: Current password
AddPlayer: Add player
PlayerAdded: Player added
AddPlayerFail: Adding the player failed
ChoosePlayer: Choose player
Previous: Previous
Next: Next
Handicaps: Handicaps
HandicapResults: Handicapped results
Serie: Serie
Groups: Groups
HoleScores: Hole scores
GroupNumber group@Int: Group #{show group}
Edit: Edit
Save: Save
Cancel: Cancel
Remove: Delete
HoleNumber hole@Int: Hole #{show hole}
RecaptchaError: reCAPTCHA error
User: User
Permissions: Permissions
MissingPermission: You do not have enough permissions
AllCompetitions: All competitions
Confirm: Confirm
ConfirmPlayerRemoveTitle: Confirm the player's removal
ConfirmSignUpRemoveTitle: Confirm the cancellation of sign-up
SignUps: Sign-ups
Competitions: Competitions
EmailExists: Another user with the same email exists
LayoutExists: Layout already exists
EditCompetition: Edit competition
CompetitionUpdated: Competition updated
CompetitionStartedError: You are not allowed to modify competition once it is started
InputScores: Input scores
NotRoundOne: You can only add player to the first round
ScoreInputNotAllowed: Score input is not allowed
ConfirmEmailSignature: Thank you
ConfirmEmailMessage: Please confirm your email address by clicking on the link below.
ScoreLog: Score log
UpdatedScores: Updates scores
Player: Player
Time: Time
New: New
ConfirmNextRoundTitle: Confirm the change to next round
ConfirmFinishCompetitionTitle: Confirm the finishing of the competition
ScoreInputError: Score input failed. Please reload the page.
EventLog: Event log
Level: Level
Event: Event
ConfirmStartCompetitionTitle: Confirm the starting of the competition
Verified: Account is verified
NotVerified: Account is not verified
SignUpNotAllowed: Sign-up not allowed
EditScores: Edit scores
Forbidden: Forbidden
CompetitionPassword: Competition password
ScoreRangeError: Score is not within allowed range (0-99)
ScoreMissing: Missing score
InputNumber: Input number
ImportPlayers: Import players
PlayersImported: Players imported
PlayersImportError err@Text: Player import failed: #{err}
AddPlayers: Add players
PDGACompetition: PDGA competition
UserIsNotRealUser: User is not real user
PDGAScores: PDGA scores
UserNoPDGANumber: User does not have a PDGA number
NotPDGACompetition: Competition is not a PDGA competition
PrivateCompetition: Private competition
CompetitionUrl: Competition URL
PDGANumber: PDGA number
NegativePDGANumber: PDGA number can't be negative
LockCompetition: Lock competition
OpenCompetition: Open competition
CompetitionLocked: Competition locked
CompetitionOpened: Competition opened
PenaltyShort: P
SuddenDeathShort: SD
Result: Result
PenaltyRangeError: Penalty can't be negative
NoVerKey: User does not have a verification key
SendVerEmail: Send verification email
ForgotPassword: Forgot password?
CompetitionDoesNotHaveRounds: Competition does not have rounds
CantRevertDnf: Can't revert DNF of the player
DnfReverted: DNF reverted
AddGroup: Add group
InputGroupNumber: Group number
InputInteger: Input an integer