LogIn: Login
LogOut: Logout
Register: Register
Notifications: Notifications
ActiveCompetitions: Active competitions
OpenSignUps: Open sign-ups
PastCompetitions: Past competitions
FutureCompetitions: Future competitions
Results: Results
Back: Back
Hole: Hole
Round: Round
Total: Total
MPO: Open
FPO: Women
Password: Password
Courses: Courses
Series: Series
Users: Users
Homepage: Homepage
NewCompetition: New competition
NewCourse: New course
Layouts: Layouts
Pars: Pars
HeadAdmins: Head Admins
Admins: Admins
AddCourse: Add course
CourseName: Course name
AddSerie: Add serie
SerieName: Serie name
AddCompetition: Add competition
Layout: Layout
Date: Date
CompetitionName: Competition name
PlayerLimit: Player limit
Notification: Notification
AddNotification: Add notification
Admin: Admin
Update: Update
Name: Name
Email: Email
Division: Division
SignUp: Sign up
FinishCompetition: Finish competition
NextRound: Next round
StartCompetition: Start competition
UpdateLayout: Update layout
AddLayout: Add layout
LayoutName: Layout name
LayoutDesc: Layout description
NumberOfHoles: Number of holes
NotAdmin: You must be an admin
NotSuperAdmin: You must be a super admin
SignUpSuccess: Signed up succesfully
SignUpFail: Sign up failed
UserUpdatedSuccess: User updated
FormMissing: Error: Form missing
FormFailure err@Text: Error: #{err}
NotPresent: Not present
Present: Present
Information: Information
AdminPanel: Admin panel
WrongAnswer: Wrong answer
ReloadPage: Reload the page if the scores change
DNF: DNF
CompetitionAdded: Competition added
CompetitionStarted: Competition started
CompetitionFinished: Competition finished
NextRoundChanged: Next round changed
ProfileUpdated: Profile updated
ProfileUpdateFailure: Profile update failed
Profile: Profile
NotificationAdded: Notification added
SerieAdded: Serie added
CourseAdded: Course added
LayoutAdded: Layout added
LayoutUpdated: Layout updated
Group: Group
Send: Send
CurrentPassword: Current password
AddPlayer: Add player
PlayerAdded: Player added
AddPlayerFail: Adding the player failed
ChoosePlayer: Choose player
Previous: Previous
Next: Next
Handicaps: Handicaps
HandicapResults: Handicapped results
Serie: Serie
Groups: Groups
HoleScores: Hole scores
GroupNumber group@Int: Group #{show group}
Edit: Edit
Save: Save
Cancel: Cancel
Remove: Delete
HoleNumber hole@Int: Hole #{show hole}
RecaptchaError: reCAPTCHA error
User: User
Permissions: Permissions
MissingPermission: You do not have enough permissions
AllCompetitions: All competitions
Confirm: Confirm
ConfirmPlayerRemoveTitle: Confirm the player's removal
ConfirmSignUpRemoveTitle: Confirm the cancellation of sign-up
SignUps: Sign-ups
Competitions: Competitions
EmailExists: Another user with the same email exists
