LogIn: Kirjaudu sisään
LogOut: Kirjaudu ulos
Register: Rekisteröidy
Notifications: Ilmoitukset
ActiveCompetitions: Käynnissä olevat kilpailut
OpenSignUps: Avoimet ilmoittautumiset
PastCompetitions: Menneet kilpailut
FutureCompetitions: Tulevat kilpailut
Results: Tulokset
Back: Takaisin
Hole: Väylä
Round: Kierros
Total: Yhteensä
MPO: Avoin
FPO: Naiset
MPM: Seniorit-40
MJ1: Juniorit-19
MJ2: Juniorit-16
MA2: Amateur Intermediate
MA3: Amateur Recreational
Password: Salasana
Courses: Radat
Series: Sarjat
Users: Käyttäjät
Homepage: Etusivu
NewCompetition: Uusi kilpailu
NewCourse: Uusi rata
Layouts: Layoutit
Pars: Väylien ihannetulokset
HeadAdmins: Pääylläpitäjät
Admins: Ylläpitäjät
AddCourse: Lisää rata
CourseName: Radan nimi
AddSerie: Lisää sarja
SerieName: Sarjan nimi
AddCompetition: Lisää kilpailu
Layout: Layout
Date: Päivämäärä
CompetitionName: Kilpailun nimi
PlayerLimit: Pelaajamäärä
Notification: Ilmoitus
AddNotification: Lisää ilmoitus
Admin: Ylläpitäjä
Update: Päivitä
Name: Nimi
Email: Sähköposti
Division: Luokka
Divisions: Luokat
SignUp: Ilmoittaudu
FinishCompetition: Lopeta kilpailu
NextRound: Seuraava kierros
StartCompetition: Aloita kilpailu
UpdateLayout: Päivitä layout
AddLayout: Lisää layout
LayoutName: Layoutin nimi
LayoutDesc: Layoutin kuvaus
NumberOfHoles: Väylien määrä
NotAdmin: Sinun pitää olla ylläpitäjä
NotSuperAdmin: Sinun pitää olla pääylläpitäjä
SignUpSuccess: Ilmoittautuminen onnistui
SignUpFail: Ilmoittautuminen epäonnistui
SignUpWrongPassword: Virheellinen kilpailun salasana
UserUpdatedSuccess: Käyttäjän tiedot päivitetty
FormMissing: Virhe: Lomake puuttuu
FormFailure err@Text: Virhe: #{err}
NotPresent: Ei paikalla
Present: Paikalla
Information: Tiedot
AdminPanel: Hallinta
WrongAnswer: Väärä vastaus
ReloadPage: Päivitä sivu automaattisesti
DNF: DNF
CompetitionAdded: Kilpailu lisätty
CompetitionStarted: Kilpailu aloitettu
CompetitionFinished: Kilpailu lopetettu
NextRoundChanged: Seuraava kierros vaihdettu
NextRoundScoresMissing: Seuraava kierrosta ei voitu vaihtaa, koska kaikkia tuloksia ei ole lisätty
FinishCompetitionScoresMissing: Kilpailua ei voitu lopettaa, koska kaikkia tuloksia ei ole lisätty
ProfileUpdated: Profiili päivitetty
ProfileUpdateFailure: Profiilin päivitys epäonnistui
Profile: Profiili
NotificationAdded: Ilmoitus lisätty
SerieAdded: Sarja lisätty
CourseAdded: Rata lisätty
LayoutAdded: Layout lisätty
LayoutUpdated: Layout päivitetty
Group: Ryhmä
Send: Lähetä
CurrentPassword: Nykyinen salasana
AddPlayer: Lisää pelaaja
PlayerAdded: Pelaaja lisätty
AddPlayerFail: Pelaajan lisääminen epäonnistui
ChoosePlayer: Valitse pelaaja
Previous: Edellinen
Next: Seuraava
Handicaps: Tasoitukset
HandicapResults: Tasoitetut tulokset
Serie: Sarja
Groups: Ryhmät
HoleScores: Väylätulokset
GroupNumber group@Int: Ryhmä #{show group}
Edit: Muokkaa
Save: Tallenna
Cancel: Peruuta
Remove: Poista
HoleNumber hole@Int: Väylä #{show hole}
RecaptchaError: reCAPTCHA virhe
User: Käyttäjä
Permissions: Oikeudet
MissingPermission: Sinulla ei ole riittäviä oikeuksia
AllCompetitions: Kaikki kilpailut
Confirm: Vahvista
ConfirmPlayerRemoveTitle: Vahvista pelaajan poistaminen
ConfirmSignUpRemoveTitle: Vahvista ilmoittautumisen peruutus
SignUps: Ilmoittautumiset
Competitions: Kilpailut
EmailExists: Toinen käyttäjä samalla sähköpostiosoitteella on jo olemassa
LayoutExists: Layout on jo olemassa
EditCompetition: Muokkaa kilpailua
CompetitionUpdated: Kilpailu päivitetty
CompetitionStartedError: Et voi muokata aloitettua kilpailua
InputScores: Syötä tuloksia
NotRoundOne: Voit lisätä pelaajan vain ensimmäiselle kierrokselle
ScoreInputNotAllowed: Tuloksen syöttäminen ei ole sallittua
ConfirmEmailSignature: Kiitos
ConfirmEmailMessage: Vahvista sähköpostiosoitteesi painamalla alla olevaa linkkiä.
ScoreLog: Tulosloki
UpdatedScores: Muokatut tulokset
Player: Pelaaja
Time: Aika
New: Uusi
ConfirmNextRoundTitle: Vahvista seuraavalle kierrokselle siirtyminen
ConfirmFinishCompetitionTitle: Vahvista kilpailun lopetus
ScoreInputError: Tuloksen syöttäminen epäonnistui. Lataa sivu uudestaan.
EventLog: Tapahtumaloki
Level: Taso
Event: Tapahtuma
ConfirmStartCompetitionTitle: Vahvista kilpailun aloittaminen
Verified: Tunnus on vahvistettu
NotVerified: Tunnusta ei ole vahvistettu
SignUpNotAllowed: Ilmoittautuminen ei ole sallittua
EditScores: Muokkaa tuloksia
Forbidden: Kielletty
CompetitionPassword: Kilpailun salasana
ScoreRangeError: Tulos ei ole sallitulla alueella (0-99)
ScoreMissing: Tulos puuttuu
InputNumber: Syötä numero
ImportPlayers: Syötä pelaajia
PlayersImported: Pelaajat lisätty
PlayersImportError err@Text: Pelaajien lisäys epäonnistui: #{err}
AddPlayers: Lisää pelaajat
PDGACompetition: PDGA kilpailu
UserIsNotRealUser: Käyttäjä ei ole oikea käyttäjä
PDGAScores: PDGA tulokset
UserNoPDGANumber: Käyttäjällä ei ole PDGA numeroa
NotPDGACompetition: Kilpailu ei ole PDGA kilpailu
PrivateCompetition: Yksityinen kilpailu
CompetitionUrl: Kilpailun osoite
PDGANumber: PDGA numero
NegativePDGANumber: PDGA numero ei voi olla negatiivinen
LockCompetition: Lukitse kilpailu
OpenCompetition: Avaa kilpailu
CompetitionLocked: Kilpailu lukittu
CompetitionOpened: Kilpailu avattu
PenaltyShort: R
SuddenDeathShort: SD
Result: Tulos