LogIn: Kirjaudu sisään
LogOut: Kirjaudu ulos
Register: Rekisteröidy
Notifications: Ilmoitukset
ActiveCompetitions: Käynnissä olevat kilpailut
OpenSignUps: Avoimet ilmoittautumiset
PastCompetitions: Menneet kilpailut
FutureCompetitions: Tulevat kilpailut
Results: Tulokset
Back: Takaisin
Hole: Väylä
Round: Kierros
Total: Yhteensä
MPO: Avoin
FPO: Naiset
Password: Salasana
Courses: Radat
Series: Sarjat
Users: Käyttäjät
Homepage: Etusivu
NewCompetition: Uusi kilpailu
NewCourse: Uusi rata
Layouts: Layoutit
Pars: Väylien ihannetulokset
HeadAdmins: Pääylläpitäjät
Admins: Ylläpitäjät
AddCourse: Lisää rata
CourseName: Radan nimi
AddSerie: Lisää sarja
SerieName: Sarjan nimi
AddCompetition: Lisää kilpailu
Layout: Layout
Date: Päivämäärä
CompetitionName: Kilpailun nimi
PlayerLimit: Pelaajamäärä
Notification: Ilmoitus
AddNotification: Lisää ilmoitus
Admin: Ylläpitäjä
Update: Päivitä
Name: Nimi
Email: Sähköposti
Division: Luokka
SignUp: Ilmoittaudu
FinishCompetition: Lopeta kilpailu
NextRound: Seuraava kierros
StartCompetition: Aloita kilpailu
UpdateLayout: Päivitä layout
AddLayout: Lisää layout
LayoutName: Layoutin nimi
LayoutDesc: Layoutin kuvaus
NumberOfHoles: Väylien määrä
NotAdmin: Sinun pitää olla ylläpitäjä
NotSuperAdmin: Sinun pitää olla pääylläpitäjä
BotCheckQuestion: Kuinka paljon on 2 plus 3?
BotCheckField: Tarkistus
SignUpSuccess: Ilmoittautuminen onnistui
SignUpFail: Ilmoittautuminen epäonnistui
UserUpdatedSuccess: Käyttäjän tiedot päivitetty
FormMissing: Virhe: Lomake puuttuu
FormFailure err@Text: Virhe: #{err}
NotPresent: Ei paikalla
Present: Paikalla
Information: Tiedot
AdminPanel: Hallinta
WrongAnswer: Väärä vastaus
ReloadPage: Lataa sivu uudestaan tulosten muuttuessa
DNF: DNF
CompetitionAdded: Kilpailu lisätty
CompetitionStarted: Kilpailu aloitettu
CompetitionFinished: Kilpailu lopetettu
NextRoundChanged: Seuraava kierros vaihdettu
ProfileUpdated: Profiili päivitetty
ProfileUpdateFailure: Profiilin päivitys epäonnistui
Profile: Profiili
NotificationAdded: Ilmoitus lisätty
SerieAdded: Sarja lisätty
CourseAdded: Rata lisätty
LayoutAdded: Layout lisätty
LayoutUpdated: Layout päivitetty
Group: Ryhmä
Send: Lähetä
CurrentPassword: Nykyinen salasana
AddPlayer: Lisää pelaaja
PlayerAdded: Pelaaja lisätty
AddPlayerFail: Pelaajan lisääminen epäonnistui
ChoosePlayer: Valitse pelaaja
Previous: Edellinen
Next: Seuraava
Handicaps: Tasoitukset
HandicapResults: Tasoitetut tulokset
Serie: Sarja
Groups: Ryhmät
HoleScores: Väylätulokset
GroupNumber group@Int: Ryhmä #{show group}
Edit: Muokkaa
Save: Tallenna
Cancel: Peruuta
Remove: Poista