Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://dev.habuu.me:3000"
  copyright: Insert copyright statement here
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "https://dev.habuu.me"
  <<: *defaults
