Default: &defaults
  database: weeklyapp.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: weeklyapp_test.sqlite3
  <<: *defaults

Staging:
  database: weeklyapp_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: weeklyapp_production.sqlite3
  poolsize: 100
  <<: *defaults
