Default: &defaults
  database: weeklyapp2.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: weeklyapp2_test.sqlite3
  <<: *defaults

Staging:
  database: weeklyapp2_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: weeklyapp2_production.sqlite3
  poolsize: 100
  <<: *defaults
